services:
  vite-front:
    container_name: vite-front-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5172:5173"